### ISSUE TITLE
New mirror in Russia

### ISSUE THREAD

**Issue by FreeSoftRussia** [ruby/bugs.ruby-lang.org#106]
it's Sofia from FreeSoft website. This is the oldest in Russia Internet resource which provides wide variety of soft for download. Our monthly audience is more than one million visitors. 
 
We have several your products in our catalogue . You can check it by the link https://freesoft.ru/author/33691 

Could you add our site to the list of your mirrors in Russia. What should we do for it?
 
Thank you in advance for your reply!

**Comment by hsbt** [comment]
Can you file your request to https://github.com/ruby/www.ruby-lang.org? Thanks.
