### ISSUE TITLE
Getting crash when I running 'bundle exec rake db:create:all'

### ISSUE THREAD

**Issue by iTamilan** [ruby/bugs.ruby-lang.org#109]
Pls find the crash report
[ruby_2019-12-18-162116_Tamils-Pro.crash.zip](https://github.com/ruby/bugs.ruby-lang.org/files/3977986/ruby_2019-12-18-162116_Tamils-Pro.crash.zip)

**Comment by hsbt** [comment]
This repository is NOT the Ruby language tracker. Can you file it to https://bugs.ruby-lang.org/ ?
