### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by mpapis** [ruby/bugs.ruby-lang.org#50]
visiting https://bugs.ruby-lang.org/ I get:

> Secure Connection Failed
> 
> An error occurred during a connection to bugs.ruby-lang.org. SSL received a record that exceeded the maximum permissible length.
> 
> (Error code: ssl_error_rx_record_too_long)
> - The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> - Please contact the website owners to inform them of this problem. Alternatively, use the command found in the help menu to report this broken site.

I'm using Firefox 26.0 from openSUSE 13.1, the site works in `curl`/`w3m`/`konqueror`, but not in `firefox`.

**Comment by hsbt** [comment]
Couldn't reproduce at 2017.
