### ISSUE TITLE
Can't update ticket with the "Edit" button

### ISSUE THREAD

**Issue by chancancode** [ruby/bugs.ruby-lang.org#60]
After clicking the edit button, this is what you get:

![screenshot](http://cl.ly/akWS/Feature__11087__Method_to_retrieve_%7Blocal_global_instance%7D_variables_as_a_Hash_-_Ruby_trunk_-_Ruby_Issue_Tracking_System.png)

**Comment by hsbt** [comment]
I added edit grant into register users.

**Comment by zzak** [comment]
@hsbt How do I edit my post? 
Clicking "Edit" still takes me to post a new message

**Comment by hsbt** [comment]
Please click-down following point.

![screenshot 2015-05-17 09 27 28](https://cloud.githubusercontent.com/assets/12301/7668507/a039527e-fc77-11e4-9836-38b72673dc78.png)

I'm NOT redmine's support center. Please investigate to redmine's function by yourself.

**Comment by zzak** [comment]
@hsbt 了解です！見つけましたー

**Comment by hsbt** [comment]
:+1:
