### ISSUE TITLE
Can't create new issue with error: "% Done is not included in the list"

### ISSUE THREAD

**Issue by wanabe** [ruby/bugs.ruby-lang.org#61]
Hello bugs.ruby-lang.org team,

I tried to create a issue to ruby-trunk, but couldn't.
redirected to edit new issue page and "% Done is not included in the list" error was shown.

Anyone can teach me what was happened and how to avoid the error?
And What additional information should I submit for this issue?

**Comment by hsbt** [comment]
Thank you for reporting.

I can reproduce it. I changed some configuration on redmine. Can you try to create new issue?

**Comment by wanabe** [comment]
I have successed to create a issue.
Thanks a lot!
