### ISSUE TITLE
Segfault on FreeBSD with v3.2.1.

### ISSUE THREAD

**Issue by dmilith** [ruby/bugs.ruby-lang.org#65]
Here's full trace -
https://gist.github.com/dmilith/a86adfc3327f692471108e979f96274c

Definition used as a base for Ruby23 (includes build options used and environment details): https://bitbucket.org/verknowsys/sofin-definitions/src/da23b5d3067320523c1acb8cef940b089b1be87b/definitions/ruby21.def

Ruby22 and Ruby21 - (used same definition as a base) work just fine.

**Comment by hsbt** [comment]
This is not language tracker. Please submit it to https://bugs.ruby-lang.org
