### ISSUE TITLE
how can get terminal's output without expect

### ISSUE THREAD

**Issue by deepvyas2016** [ruby/bugs.ruby-lang.org#67]
PTY.spawn("telnet ip port") do |ssh_read,ssh_write,pid|
                ssh_write.puts("ifconfig")
                ssh_read.expect("#"){|msg| puts msg}
end
how to get the output of "ifconfig " without using ssh_read.expect.

**Comment by hsbt** [comment]
This is not language tracker. Please submit it to [stackoverflow](http://stackoverflow.com/)
