### ISSUE TITLE
Calculation issue - Ruby 2.2.2 shows 1 - 0.9 as 0.09999999999999998 

### ISSUE THREAD

**Issue by ff-cviradiya** [ruby/bugs.ruby-lang.org#69]
2.2.2 :001 > 1 - 0.9
 => 0.09999999999999998 

Shouldn't this be simply 0.1 ? or Am I missing something ?

**Comment by nurse** [comment]
Please learn floating point numbers:

What Every Computer Scientist Should Know About Floating-Point Arithmetic
http://download.oracle.com/docs/cd/E19957-01/806-3568/ncg_goldberg.html
http://wiki.github.com/rdp/ruby_tutorials_core/ruby-talk-faq#floats_imprecise
http://en.wikipedia.org/wiki/Floating_point#Accuracy_problems

**Comment by wesinator** [comment]
The updated wiki faq link is https://github.com/rdp/ruby_tutorials_core/wiki/Ruby-Talk-FAQ#floats_imprecise

https://www.rubyguides.com/2016/07/numbers-in-ruby/ gives a good overview
