### ISSUE TITLE
Licence issue with use of Onigmo rather than Oniguruma library files!!!

### ISSUE THREAD

**Issue by SlySven** [ruby/bugs.ruby-lang.org#75]
I am not sure if this is the correct place to report it but I am not a member of https://bugs.ruby-lang.org/ and was not minded to join up just to query/report one thing.  I am concerned about the current content of https://github.com/ruby/ruby/blob/trunk/LEGAL which implies that Ruby is using [Oniguruma](https://github.com/kkos/oniguruma) when in fact the forked [Onigmo](https://github.com/k-takata/Onigmo) is what is in place - the licence of both are ___BSD___ (AFAICT) but the details listed in that file for the selected files used in Ruby are for the former rather than the latter library and as such __do not comply with the terms of that type of licence__ (IMHO but IANAL). 😮

**Comment by hsbt** [comment]
Please report to bugs.ruby-lang.org. This repository is tracker's issue. Not the Ruby language issue.

**Comment by SlySven** [comment]
🆗 have done so...

**Comment by hsbt** [comment]
Confirmed. Thanks!
