### ISSUE TITLE
bugs.ruby-lang.org の https の証明書

### ISSUE THREAD

**Issue by znz** [ruby/bugs.ruby-lang.org#76]
not after まで残り2週間を切りましたが、GlobalSign の証明書から Let's Encrypt に移行して SANs (Subject Alternative Names) に redmine.ruby-lang.org を入れるようにして、古い redmine.ruby-lang.org を指している URL を救済するのはどうでしょうか?

現状は `http://redmine.ruby-lang.org` を指していても bugs.ruby-lang.org にリダイレクトされる前に https にリダイレクトされて証明書エラーになって、証明書エラーを無視しないと `https://bugs.ruby-lang.org` にはたどり着けないという状態です。

**Comment by hsbt** [comment]
bugs.ruby-lang.org は heroku で動かしているんですが、heroku で手動で Let's Encrypt って使えるんでしょうか? 僕はその方法を知らないので、もしあれば教えて欲しいです。

後、bugs.ruby-lang.org は今年から heroku の Automated Certificate(中身は Let's Encrypt) を使おうと思っていました。

https://devcenter.heroku.com/articles/automated-certificate-management

**Comment by hsbt** [comment]
今日 heroku の Automated Certificate 使って https://redmine.ruby-lang.org/ もちゃんと Verify な証明書を使うようにしたんですが、これだとどうでしょう?

良さそうということならクローズをお願いします。

**Comment by znz** [comment]
証明書は良さそうなので、close します。
証明書を見た感じだと heroku のそれは Let's Encrypt を使って、複数ドメインだと SANs を使っていて、certbot などで複数ドメイン対応の証明書にするのと同じっぽいです。

URL を統一する方向なら、 redmine.ruby-lang.org から bugs.ruby-lang.org へのリダイレクトがあると良さそうに思いました。
