### ISSUE TITLE
Feature request: win32/registry for defining the KEY_WOW64_{32,64}KEY flags 

### ISSUE THREAD

**Issue by psaxena** [ruby/bugs.ruby-lang.org#89]
Ruby win32/registry is not defining the KEY_WOW64_{32,64}KEY flags. Currently it has to be used by opening module and adding constant to read 32 and 64 bit application path.

module Win32::Registry::Constants
  KEY_WOW64_64KEY = 0x0100
  KEY_WOW64_32KEY = 0x0200
end
To read a 64-bit key:

reg = Win32::Registry::HKEY_LOCAL_MACHINE.open('SOFTWARE\app_path',
        Win32::Registry::KEY_READ | Win32::Registry::KEY_WOW64_64KEY)
To read a 32-bit key:

reg = Win32::Registry::HKEY_LOCAL_MACHINE.open('SOFTWARE\app_path',
        Win32::Registry::KEY_READ | Win32::Registry::KEY_WOW64_32KEY)

**Comment by nurse** [comment]
This is not the language issue tracker. Please submit https://bugs.ruby-lang.org.
